
"""add api_key to users
"""

revision = <mako.runtime.Undefined object at 0x00000266DCA30C10>
down_revision = '0002_add_api_key'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('daily_usage', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='fraudguard'
    )
    op.create_index(op.f('ix_fraudguard_users_api_key'), 'users', ['api_key'], unique=True, schema='fraudguard')
    op.create_index(op.f('ix_fraudguard_users_email'), 'users', ['email'], unique=True, schema='fraudguard')
    op.create_index(op.f('ix_fraudguard_users_id'), 'users', ['id'], unique=False, schema='fraudguard')
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['fraudguard.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fraudguard'
    )
    op.create_index(op.f('ix_fraudguard_transactions_id'), 'transactions', ['id'], unique=False, schema='fraudguard')
    op.drop_index(op.f('idx_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', postgresql.CITEXT(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("'FREE'::text"), autoincrement=False, nullable=False),
    sa.Column('daily_usage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='users_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('idx_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_fraudguard_transactions_id'), table_name='transactions', schema='fraudguard')
    op.drop_table('transactions', schema='fraudguard')
    op.drop_index(op.f('ix_fraudguard_users_id'), table_name='users', schema='fraudguard')
    op.drop_index(op.f('ix_fraudguard_users_email'), table_name='users', schema='fraudguard')
    op.drop_index(op.f('ix_fraudguard_users_api_key'), table_name='users', schema='fraudguard')
    op.drop_table('users', schema='fraudguard')
    # ### end Alembic commands ###
